### ISSUE TITLE
CKeditor5 v12 upgrade

### ISSUE THREAD

**Issue by frega** [AmazeeLabs/ckeditor5_sections#6]
Hi Amazees, 

first of: I really, really like the approach taken in this (suite of) module. WYSIWYG editors have had a bad reputation for a reason but the mere possibilty of using webcomponents or the prospect of collaborative editing make me rather giddy :)

I struggled a bit to get a development environment set up that would allow to tinker (and create tests) with the modules that make up `ckeditor5_sections`. 

I thus ultimately upgraded to the latest ckeditor5 v12. I am aware that that v12 introduces several breaking changes but was able to get all tests to pass with relatively minor changes. Please see my fork of the [CKeditor repo](https://github.com/frega/ckeditor5/tree/ckeditor5v12) which pulls in the ckeditor5-`master` as well as the upgraded forks for [ckeditor5-drupal-media](https://github.com/frega/ckeditor5-drupal-media/tree/ckeditor5v12), [ckeditor5-drupal-linkit](https://github.com/frega/ckeditor5-drupal-media/tree/ckeditor5v12), [ckeditor5-template](https://github.com/frega/ckeditor5-template/tree/ckeditor5v12). 

The tests are green (adjusting some output in a few limited cases) - but I certainly would not claim to have fully grokked all that is going on. As I couldn't get the tests to run in the current setup, I wasn't either fully able to check all manual tests and there remain some CSS that isn't properly resolved (on running `yarn run manual`).

To review please clone the [main repo](https://github.com/frega/ckeditor5/tree/ckeditor5v12) and run tests. 
1. `git clone git@github.com:frega/ckeditor5.git --branch ckeditor5v12 ; cd ckeditor5`
2. `mgit sync` 
3. `yarn install` 
4. Followed by `yarn run manual` and `yarn run test --files=template && yarn run test --files=drupal-media && yarn run test --files=drupal-linkit`.

Let me know what your plan with regard to CKeditor5 v12 is and whether you'd like me to open PRs in the respective (sub)repositories.

Best, Fredrik

**Comment by pmelab** [comment]
Hi Fredrik!

I'm sorry for the late response, but since this is heavily worked on and we didn't actively advertise it, I didn't expect anybody to jump on it 😄 

The more I'm impressed that you were able to figure it out without any guidance or documentation!

In the last weeks we figured out how powerful custom web components are in this context, and the current plan is to eventually sunset the media and linkit packages and drastically slim the templates package down to pure document model management. All the UI heavy components (buttons, media previews, containers, tabs, galleries ...) become pure web components and therefore easier to maintain and compose.

After this "reduction" we probably also would upgrade ckeditor packages.

If you are interested in this project contact us on drupal slack! I would love to get some more opinions.

**Comment by frega** [comment]
@pmelab - i've rerolled and incorporated the changes from the "great cleanup".
happy to open a PR against `ckeditor5-template` if you think it makes sense. The required changes are moderate (https://github.com/AmazeeLabs/ckeditor5-template/compare/master...frega:ckeditor5v12) but could probably benefit from a little coordinated refactoring.

To test this in context I suggest these steps to review: 

1. `git clone git@github.com:frega/ckeditor5.git --branch ckeditor5v12` ; `cd ckeditor5`
2. `mgit sync` # might require `npm install -g mgit2` 
3. `yarn install`
4. Followed by `yarn run manual` opening http://localhost:8125/ckeditor5-build-drupal-sections/tests/manual/ckeditor.html
5. `yarn run test --files=template` (drupal-media and drupal-linkit have been dropped)

**Comment by pmelab** [comment]
Has already been merged some time ago. Thanks again 😄
